import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type CartProduct = { productId: string; name: string; price: number; image: string; category: string; color?: string }; export type CartItem = CartProduct & { quantity: number };
type Value = { cartItems: CartItem[]; addToCart: (p: CartProduct, q?: number) => void; removeFromCart: (id: string) => void; increaseQuantity: (id: string) => void; decreaseQuantity: (id: string) => void; clearCart: () => void; removePurchasedItems: (ids: string[]) => void; cartCount: number; subtotal: number; selectedProductIds: string[]; toggleSelection: (id: string) => void; selectAll: () => void; deselectAll: () => void; isSelected: (id: string) => boolean; selectedItems: CartItem[]; selectedSubtotal: number };
const CartContext = createContext<Value | undefined>(undefined); const cartKey = "dulce-cart"; const selectionKey = "dulce-selected-products";
function readCart(): CartItem[] { try { const data: unknown = JSON.parse(localStorage.getItem(cartKey) || "[]"); if (!Array.isArray(data)) return []; return data.flatMap((x): CartItem[] => { if (!x || typeof x !== "object") return []; const i = x as Record<string, unknown>; const productId = typeof i.productId === "string" ? i.productId : typeof i.id === "string" ? i.id : ""; if (!productId || typeof i.name !== "string" || typeof i.category !== "string" || typeof i.image !== "string" || typeof i.price !== "number" || typeof i.quantity !== "number" || i.quantity < 1) return []; return [{ productId, name: i.name, category: i.category, image: i.image, price: i.price, quantity: i.quantity, color: typeof i.color === "string" ? i.color : undefined }]; }); } catch { localStorage.removeItem(cartKey); return []; } }
export function CartProvider({ children }: { children: ReactNode }) { const [cartItems, setCartItems] = useState<CartItem[]>([]); const [selectedProductIds, setSelected] = useState<string[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const cart = readCart(); const stored = sessionStorage.getItem(selectionKey); setCartItems(cart); setSelected(stored ? (JSON.parse(stored) as unknown[]).filter((id): id is string => typeof id === "string" && cart.some((item) => item.productId === id)) : cart.map((item) => item.productId)); setReady(true); }, 0); return () => clearTimeout(timer); }, []);
  useEffect(() => { if (ready) { localStorage.setItem(cartKey, JSON.stringify(cartItems)); sessionStorage.setItem(selectionKey, JSON.stringify(selectedProductIds)); } }, [cartItems, selectedProductIds, ready]);
  const addToCart = (p: CartProduct, q = 1) => { setCartItems((items) => items.some((i) => i.productId === p.productId) ? items.map((i) => i.productId === p.productId ? { ...i, quantity: i.quantity + q } : i) : [...items, { ...p, quantity: q }]); setSelected((ids) => ids.includes(p.productId) ? ids : [...ids, p.productId]); };
  const removeFromCart = (id: string) => { setCartItems((items) => items.filter((i) => i.productId !== id)); setSelected((ids) => ids.filter((x) => x !== id)); }; const increaseQuantity = (id: string) => setCartItems((items) => items.map((i) => i.productId === id ? { ...i, quantity: i.quantity + 1 } : i)); const decreaseQuantity = (id: string) => setCartItems((items) => items.flatMap((i) => i.productId !== id ? i : i.quantity > 1 ? { ...i, quantity: i.quantity - 1 } : [])); const clearCart = () => { setCartItems([]); setSelected([]); }; const removePurchasedItems = (ids: string[]) => { setCartItems((items) => items.filter((i) => !ids.includes(i.productId))); setSelected((selected) => selected.filter((id) => !ids.includes(id))); };
  const value = useMemo(() => { const selectedItems = cartItems.filter((i) => selectedProductIds.includes(i.productId)); return { cartItems, addToCart, removeFromCart, increaseQuantity, decreaseQuantity, clearCart, removePurchasedItems, cartCount: cartItems.reduce((n, i) => n + i.quantity, 0), subtotal: cartItems.reduce((n, i) => n + i.price * i.quantity, 0), selectedProductIds, toggleSelection: (id: string) => setSelected((ids) => ids.includes(id) ? ids.filter((x) => x !== id) : [...ids, id]), selectAll: () => setSelected(cartItems.map((i) => i.productId)), deselectAll: () => setSelected([]), isSelected: (id: string) => selectedProductIds.includes(id), selectedItems, selectedSubtotal: selectedItems.reduce((n, i) => n + i.price * i.quantity, 0) }; }, [cartItems, selectedProductIds]); return <CartContext.Provider value={value}>{children}</CartContext.Provider>; }
export function useCart() { const value = useContext(CartContext); if (!value) throw new Error("useCart must be used inside CartProvider"); return value; }
