import Head from "next/head";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { ArrowLeft, CreditCard } from "lucide-react";
import { useCart } from "@/context/CartContext";
import styles from "@/styles/Checkout.module.css";
const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const serviceFee = 3000;
type CreatedOrder = { checkoutId: string; subtotal: number; serviceFee: number; total: number; status: "PENDING" };

export default function PaymentPage() {
  const { cartItems, subtotal } = useCart(); const [customer, setCustomer] = useState({ name: "", email: "", phone: "" }); const [isCreating, setIsCreating] = useState(false); const [errorMessage, setErrorMessage] = useState(""); const [createdOrder, setCreatedOrder] = useState<CreatedOrder | null>(null);
  const displaySubtotal = createdOrder?.subtotal ?? subtotal; const displayServiceFee = createdOrder?.serviceFee ?? serviceFee; const displayTotal = createdOrder?.total ?? subtotal + serviceFee;
  async function createOrder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setErrorMessage(""); setIsCreating(true);
    try {
      const items = cartItems.map((item) => ({ productId: item.productId, quantity: item.quantity }));
      if (items.some((item) => !item.productId.trim() || item.quantity <= 0)) throw new Error("Your cart contains an invalid item. Please add the treat again.");
      const payload = { items, customer };
      if (process.env.NODE_ENV === "development") console.log("Creating Dulce checkout:", payload);
      const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "We could not create your order."); setCreatedOrder(result);
    } catch (error) { setErrorMessage(error instanceof Error ? error.message : "We could not create your order."); } finally { setIsCreating(false); }
  }
  return <><Head><title>Payment | Dulce</title></Head><main className={styles.page}><div className={styles.container}><header className={styles.header}><Link href="/checkout" className={styles.backButton}><ArrowLeft size={19} /> Back</Link><h1>Payment</h1><span /></header>{cartItems.length === 0 ? <section className={styles.emptyState}><div className={styles.emptyIcon}>*</div><h2>Your sweet box is still empty.</h2><p>Add treats before continuing to payment.</p><Link className={styles.primaryButton} href="/#menu">Explore treats</Link></section> : <div className={styles.checkoutLayout}><section className={styles.paymentSection}><p className={styles.eyebrow}>ALMOST THERE</p><h2>Customer information</h2><form className={styles.form} onSubmit={createOrder}><label>Name<input required value={customer.name} onChange={(event) => setCustomer({ ...customer, name: event.target.value })} placeholder="Your full name" /></label><label>Email<input type="email" required value={customer.email} onChange={(event) => setCustomer({ ...customer, email: event.target.value })} placeholder="you@example.com" /></label><label>Phone<input type="tel" required value={customer.phone} onChange={(event) => setCustomer({ ...customer, phone: event.target.value })} placeholder="08xx xxxx xxxx" /></label><div className={styles.methodCard}><CreditCard size={22} /><div><strong>Xendit</strong><span>Secure online payment</span></div><i>Next step</i></div>{errorMessage && <p className={styles.errorMessage}>{errorMessage}</p>}<button className={styles.primaryButton} type="submit" disabled={isCreating || Boolean(createdOrder)}>{isCreating ? "Creating order..." : "Create Order"}</button></form>{createdOrder && <div className={styles.successCard}><strong>Order created successfully</strong><div><span>Checkout ID</span><b>{createdOrder.checkoutId}</b></div><div><span>Subtotal</span><b>{rupiah.format(createdOrder.subtotal)}</b></div><div><span>Service Fee</span><b>{rupiah.format(createdOrder.serviceFee)}</b></div><div><span>Total</span><b>{rupiah.format(createdOrder.total)}</b></div><div><span>Status</span><b>{createdOrder.status}</b></div><button type="button" className={styles.disabledButton} disabled>Continue to Xendit</button></div>}</section><aside className={styles.summaryCard}><p className={styles.eyebrow}>YOUR ORDER</p><h2>{cartItems.length} sweet item{cartItems.length > 1 ? "s" : ""}</h2><div className={styles.miniItems}>{cartItems.map((item) => <div key={item.productId}><span>{item.name} x {item.quantity}</span><strong>{rupiah.format(item.price * item.quantity)}</strong></div>)}</div><div className={styles.summaryRow}><span>Subtotal</span><strong>{rupiah.format(displaySubtotal)}</strong></div><div className={styles.summaryRow}><span>Service Fee</span><strong>{rupiah.format(displayServiceFee)}</strong></div><div className={styles.totalRow}><span>Total</span><strong>{rupiah.format(displayTotal)}</strong></div></aside></div>}</div></main></>;
}
